spring:
  profiles:
    active: prod
  task:
    scheduling:
      pool:
        size: 5
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/imooc_escape?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000
      connection-test-query: SELECT 1
      pool-name: SpringEscapeHikariPool

ecsape:
  user:
    name: qinyi-root
    age: 19

